apiVersion: v1
kind: Service
metadata:
  name: alwayson-listener
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
    - name: endpoint
      port: 5022
      targetPort: 5022
