apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-0-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mssql-0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql-0 
    spec:
      terminationGracePeriodSeconds: 10
      securityContext: 
        fsGroup: 1000
      hostname: mssql-0
      containers: 
      - name: mssql-0  
        image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        env: 
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: MSSQL_ENABLE_HADR
          value: "1"
        - name: MSSQL_AGENT_ENABLED
          value: "true"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        resources: 
          limits:
            memory: 4G
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-0
---
apiVersion: v1
kind: Service
metadata: 
  name: mssql-0
spec: 
  selector: 
    app: mssql-0 
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
    - name: endpoint
      port: 5022
      targetPort: 5022
  type: LoadBalancer
